def test_create_category(client, admin_token):

    payload = {
        "name": "Electronics",
        "description": "Electronic products"
    }

    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.post(
        "/category/create",
        json=payload,
        headers=headers
    )

    print("Status:", response.status_code)
    print("Response:", response.json())

    assert response.status_code == 201
    data = response.json()
    assert data["name"] == "Electronics"
    assert data["description"] == "Electronic products"
    
    
def test_get_all_categories(client, admin_token):

    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        "/category/all_categories",
        headers=headers
    )

    assert response.status_code == 200

    data = response.json()

    assert isinstance(data, list)
    
    
def test_get_category_by_id(client, admin_token):

    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    # First create a category
    payload = {
        "name": "Furniture",
        "description": "Furniture products"
    }

    create_response = client.post(
        "/category/create",
        json=payload,
        headers=headers
    )

    assert create_response.status_code == 201

    # Get the ID generated by the database
    category = create_response.json()
    category_id = category["id"]

    # Now get that category
    response = client.get(
        f"/category/category/{category_id}",
        headers=headers
    )

    assert response.status_code == 200

    data = response.json()

    assert data["id"] == category_id
    assert data["name"] == "Furniture"
    assert data["description"] == "Furniture products"
    
    
def test_update_category(client, admin_token):

    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    # Create a category first
    create_payload = {
        "name": "Books",
        "description": "Book products"
    }

    create_response = client.post(
        "/category/create",
        json=create_payload,
        headers=headers
    )

    assert create_response.status_code == 201

    category = create_response.json()
    category_id = category["id"]

    # Update the category
    update_payload = {
        "name": "Updated Books",
        "description": "Updated book products"
    }

    response = client.put(
        f"/category/update_category/{category_id}",
        json=update_payload,
        headers=headers
    )

    assert response.status_code == 200

    data = response.json()

    assert data["id"] == category_id
    assert data["name"] == "Updated Books"
    assert data["description"] == "Updated book products"
    
    
    
def test_delete_category(client, admin_token):

    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    # Create category first
    payload = {
        "name": "Temporary Category",
        "description": "Category to be deleted"
    }

    create_response = client.post(
        "/category/create",
        json=payload,
        headers=headers
    )

    assert create_response.status_code == 201

    category_id = create_response.json()["id"]

    # Delete category
    response = client.delete(
        f"/category/delete_category/{category_id}",
        headers=headers
    )

    assert response.status_code == 204

    # Verify category no longer exists
    get_response = client.get(
        f"/category/category/{category_id}",
        headers=headers
    )

    assert get_response.status_code == 404
    
    
def test_create_category_without_auth(client):

    payload = {
        "name": "Unauthorized Category",
        "description": "Should not be created"
    }

    response = client.post(
        "/category/create",
        json=payload
    )

    assert response.status_code == 401
    assert response.json()["detail"] == "Authorization token is missing"
    
    
def test_create_category_as_sales_executive(client, sales_executive_token):

    payload = {
        "name": "Sales Category",
        "description": "Should not be created by sales executive"
    }

    headers = {
        "Authorization": f"Bearer {sales_executive_token}"
    }

    response = client.post(
        "/category/create",
        json=payload,
        headers=headers
    )

    assert response.status_code == 403
    assert response.json()["detail"] == "Admin privileges required"
    
    
def test_get_nonexistent_category(client, admin_token):

    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        "/category/category/999999",
        headers=headers
    )

    assert response.status_code == 404
    
    
def test_update_nonexistent_category(client, admin_token):

    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    payload = {
        "name": "Updated Category",
        "description": "Should not exist"
    }

    response = client.put(
        "/category/update_category/999999",
        json=payload,
        headers=headers
    )

    assert response.status_code == 404
    
def test_delete_nonexistent_category(client, admin_token):

    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.delete(
        "/category/delete_category/999999",
        headers=headers
    )

    assert response.status_code == 404